name: Test build

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Remove old dirs
        run: rm -rf dist build

      - name: Create wheel file
        run: python3 setup.py bundle bdist_wheel
