name: PyLint Runner

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Python Pylin GitHub Action
      uses: fylein/python-pylint-github-action@v1
      with:
        args: pip3 install -r requirements.txt && pylint --rcfile=pylintrc projector_installer/ setup.py